#  Servicio Calibre-web
services:
  calibre-web:
    container_name: multimedia-calibreweb
    image: 'linuxserver/calibre-web:latest'
    restart: always
    volumes:
      - ./config:/config:rw'
      - /volume2/libros:/books:rw'
    env_file:
      - /volume1/docker/docker/synology.env                     # variables synology (PUID, PGID, TZ)
    #  Variables calibre-web
    environment:
      - DOCKER_MODS=linuxserver/mods:universal-calibre
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1
    mem_limit: 2g
    ports:
      - '8083:8083'
    # network_mode: host
