services:
  appweb_alertas:
    container_name: 'AppWeb_Contactos_0.2'
    #  Versi칩n: 0.2 - Incorporamos las alertas en ejecutar.sh
    #  Versi칩n: 0.1 - pasamos de crearlo por Dockerfile a cratearlo en proyecto con docker-compose
    
    # Otra posibilidad es crearlo en un Dockerfile y luego hacer un build
    # build: './application'
    
    # Si no se crea con build, se puede hacer con image
    image: 'python:3.13.2'
    
    # Si es necesario asignar puertos (al tener red host no es necesario)
    # ports:
    #  - '5000:5000'
    
    volumes:
      - '/volume1/docker/Python:/usr/python:rw'
      - '/volume1/video:/video:ro'
    
    # Definir el directorio de trabajo
    working_dir: /usr/python
    
    # Usamos la red del host
    network_mode: host
    
    # Se puede reiniciar siempre o s칩lo en caso de error
    # restart: always
    restart: on-failure

    # Se pueden definir dependencias entre servicios
    # depends_on:
    #    - database

    # A침adir variables de entorno
    # environment: 
    #    - PORT=8080
    #    - DB_USER=user
    #    - DB_PASS=password
    #   o incluimos en un archivo .env
    #env_file: ./application/.env

    # Comando a ejecutar
    command: "./Appweb_contactos/ejecutar.sh"