services:
  vduplicatefinder:
    container_name: Video-Duplicate-Finder
    image: jlesage/video-duplicate-finder:latest
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 5800 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    security_opt:
      - no-new-privileges:true
    environment:
      DARK_MODE: 1
    restart: on-failure:5
    ports:
      - 4741:5800
    volumes:
      - /volume1/docker/video-duplicate-finder:/config:rw
      - /volume1:/storage:rw