#  Servicio plex - servidor multimedia
services:
  plex:
    container_name: multimedia-plex
    image: 'linuxserver/plex:latest'
    restart: unless-stopped
    volumes:
      - ./config:/config
      - /volume2/video:/movies
      #- '/volume2/video:/tv'
    env_file:
      - /volume1/docker/docker/synology.env                     # variables synology (PUID, PGID, TZ)
    #  Variables Jellyfin
    environment:
      - VERSION=docker
    devices:
      - '/dev/dri:/dev/dri'
    network_mode: host