#  Servicio bloqueador de anuncios Pi-hole
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: utilidades-pihole
    image: pihole/pihole:latest
    restart: unless-stopped
    # Añado red tipo host y quito los puertos
    network_mode: host 
    # Volumes store your data between container upgrades
    volumes:
      # For persisting Pi-hole's databases and common configuration file
      - /volume1/docker/pihole/etc-pihole:/etc/pihole
      - /volume1/docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
      # Uncomment the below if you have custom dnsmasq config files that you want to persist. Not needed for most starting fresh with Pi-hole v6. If you're upgrading from v5 you and have used this directory before, you should keep it enabled for the first v6 container start to allow for a complete migration. It can be removed afterwards
      #- /volume1/docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      # See https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      # Required if you are using Pi-hole as your DHCP server, else not needed
      - NET_ADMIN
    env_file:
      - /volume1/docker/docker/synology.env                 # variables synology (PUID, PGID, TZ)
    #  definimos variblas de opera
      - /volume1/docker/docker/utilidades/pihole.env        # variables privadas
